# Generated by Django 3.0.5 on 2020-08-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_puro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['created'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
